callstack/react-native-builder-bob

README.md
package.json
src/cli.ts
src/targets/aar.ts
src/types.ts
src/utils/androidAssemble.ts
src/utils/jetifier.ts
yarn.lock

This PR adds a target which assembles Android AAR files for a library. This is needed to help workaround the migration to AndroidX. See the discussion here for details:
https://github.com/react-native-community/discussions-and-proposals/issues/129
The idea is that we can migrate a library to AndroidX and then generate AAR files which can then be converted back to the Android Support Library using the "reverse jetty" tool.
This target automates this process by running `./gradlew assemble` and then copying the output AAR to the correct folder. This then optionally converts it to the support library using the [`jetifier`](https://github.com/mikehardy/jetifier) package.
You need to add the `aar` target to a project and then run `yarn bob build` to test the output. Example output when run:
``` …
```

feat: add a target to build Android AAR files with support for reverse Jetify

---

src/targets/aar.ts

This adds the ability to change the aar bundle name bob uses.  Instead of always expecting `android.aar` (it's still the default).

feat(aar): added configurable bundle name

---

README.md
src/targets/typescript.ts

For the typescript target, this PR aims to add an option to specify a path to tsc. We are using bob in a workspace setup. With this option, we can resolve tsc's path to the workspace root's node modules so that not the global tsc is being used. 
I've tested this fork with our setup and it works.
- [X ] I have tested this on a device and a simulator
- [N/A ] I mentioned this change in `CHANGELOG.md`
- [ X] I updated the typed files (TS and Flow)
- [N/A ] I added a sample use of the API in the example project (`example/App.js`)

feat: add option to specify tsc path

---

templates/native-library/{%= project.podspec %}.podspec

Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
| Android |    ❌     |

fix: Xcode 12 compatibility

---

templates/native-library/ios/{%= project.name %}.xcodeproj/project.pbxproj

Currently when creating Native Module package for iOS the invalid Objective-C implementation file extension (`.mm`) is provided in `project.pbxproj`. This causes the inability to open and edit the package [`.m` file](https://github.com/react-native-community/bob/tree/master/templates/objc-library/ios) in XCode.
This PR fixes that issue simply by replacing the incorrect file extension with the correct one.
After generating the project with the change I can open implementation code in the XCode.
XCode!
Generate iOS Native Project and try to open main file in XCode.
| Android |    ❌     |

fix: fix Obj-C file extension in project.pbxproj

---

templates/example/example/ios/Podfile

This fixes execution of `yarn bootstrap`
```
[!] CocoaPods could not find compatible versions for pod "react-native-awesome-module":
In Podfile:
react-native-awesome-module (from `../..`)
Specs satisfying the `react-native-awesome-module (from `../..`)` dependency were found, but they required a higher minimum deployment target.
```
```
$ npm install -g https://github.com/callstack/react-native-builder-bob#85835e6
$ /usr/local/Cellar/node/14.11.0/lib/node_modules/@react-native-community/bob/bin/bob.js create react-native-awesome-module
$ cd react-native-awesome-module
$ yarn bootstrap
```
With this fix, you won't get the Cocoapod error I reported in the summary.

Update example's Podfile minimum deployment target

---

src/create.ts
templates/common/$.yarnrc
templates/common/CONTRIBUTING.md
templates/common/scripts/bootstrap.js

Currently we need to run 'yarn bootstrap' to setup the repo. However it's easy to forget. This PR overrides the Yarn command to run the 'bootstrap' script if no arguments are specified.

chore: override yarn command to make repo setup easier

---

templates/common/$package.json

Sometimes release-it fails if publishConfig isn't specified. So this adds it to the default template.

fix: add publishConfig to make release-it work

---

src/utils/compile.ts
templates/expo-library/example/webpack.config.js

Hello I have multiple project and we use `.jsx` extension in their source code.
- Simply create a file with extension `.js`
- Copy the file with a other name and the extension `.jsx`
- Compare the output file to see that they are the same

fix: add support for 'jsx' file extention

---

README.md
templates/common/$package.json

The generated declaration file ends up in lib/typescript/index.d.ts but package.json points to lib/typescript/src/index.d.ts
1. npx react-native-builder-bob create react-native-awesome-module
2. What type of package do you want to develop? › Native module in Kotlin and Objective-C
3. run: yarn
4. Find the generated declaration file in lib/typescript/index.d.ts (not in a src folder)

fix: wrong types path

---

templates/common/example/src/App.tsx
templates/example/example/ios/Podfile
templates/native-library/{%- project.podspec %}.podspec
templates/native-view-library/src/index.tsx
templates/native-view-library/{%- project.podspec %}.podspec

A couple of related fixes to the EJS statements:
Full length EJS lines should _not_ be indented as if they were semantically on same level as the code they encapsulate. Instead, they should be considered independent statements that _assemble indented code_. Otherwise the processed files will contain whitespace errors (i.e. spaces followed by EOL).
Change the end marker `%>` to `-%>` for full line ejs statements. What this does is it will _omit_ the newline character in the processed file. Depending on the conditional path, `yarn lint` (ESLint) was failing with a double blank line, e.g.:
```
[...]/example/src/App.tsx
6:1  error  Delete `⏎`  prettier/prettier
```
Create new project and check generated files are whitespace error free. Verify `yarn lint` passes.

Fix EJS formatting issues

---

templates/example/example/babel.config.js
templates/expo-library/example/babel.config.js

Fixes HMR errors that present as `transform[stderr]: Could not resolve blah blah blah`
Closes #127
Add `extensions: ['.js', '.ts', '.json', '.jsx', '.tsx'],` to an existing project's module-resolver and HMR errors will go away

fix hmr errors

---

packages/create-react-native-library/src/index.ts

Closes https://github.com/callstack/react-native-builder-bob/issues/145
The fallback version was incorrect. This PR fixes it.
Like always :D

fix: fallback bob version

---

packages/create-react-native-library/templates/common/CONTRIBUTING.md

Fixes a broken egghead link in the CONTRIBUTING.md file.
Click on the "How to Contribute to an Open Source Project on GitHub" link in CONTRIBUTING.md

Fix broken egghead link

---

packages/create-react-native-library/templates/example/example/android/app/src/main/java/com/example/{%- project.package %}/MainApplication.java

When the Flipper is enabled, the generated code package name is wrong.
It will throw a runtime error since can't find the ReactNativeFlipper class.

Fix wrong package name of ReactNativeFlipper

---

packages/create-react-native-library/templates/example/example/android/build.gradle
packages/create-react-native-library/templates/java-library/android/build.gradle
packages/create-react-native-library/templates/java-view-library/android/build.gradle
packages/create-react-native-library/templates/kotlin-library/android/build.gradle
packages/create-react-native-library/templates/kotlin-library/android/gradle.properties
packages/create-react-native-library/templates/kotlin-view-library/android/build.gradle
packages/create-react-native-library/templates/kotlin-view-library/android/gradle.properties

Setting buildToolsVersion is no longer recommended, it'll default to Android Gradle Plugin defaults. It makes DX worse by requiring multiple versions of build tools by various dependencies require various versions.

remove buildToolsVersion

---

packages/create-react-native-library/templates/expo-library/example/$package.json

The current SDK version (40) is not working with `react-native-reanimated 2`
so this PR will solve it.
fixing #191

update expo sdk version to 42

---

packages/react-native-builder-bob/src/utils/androidAssemble.ts

This addresses [this issue](https://github.com/callstack/react-native-builder-bob/issues/79) by fixing the command used to call the gradle wrapper on Windows. 
Following the steps outlined in the issue linked above should no longer result in an error that says the gradle wrapper doesn't appear to be present.

fix: call the gradle wrapper correctly on windows

---

packages/create-react-native-library/templates/example/example/android/build.gradle
packages/create-react-native-library/templates/java-library/android/build.gradle
packages/create-react-native-library/templates/java-view-library/android/build.gradle
packages/create-react-native-library/templates/kotlin-library/android/build.gradle
packages/create-react-native-library/templates/kotlin-view-library/android/build.gradle

Recent react-native dependencies are published to Maven Central only.
Check if `mavenCentral` is above `jcenter` in repo structure 
More context here: https://github.com/react-native-camera/react-native-camera/issues/2490

fix(android): prefer downloading dependencies from Maven Central

---

packages/create-react-native-library/templates/swift-view-library/ios/{%- project.name %}ViewManager.m

according to https://github.com/expo/expo/issues/15622#issuecomment-997225774, we should use `#import <React/RCTViewManager.h>` instead of double-quoted import.
regression test by creating a test library and running the example (`yarn && yarn example ios`).

fix: remove double-quoted imports from React-Core

---

packages/create-react-native-library/templates/common/$package.json
packages/create-react-native-library/templates/common/example/metro.config.js

This pull request fixes #160 
It changes the *blacklist* to *exclusionList* in the example *metro.config.js* file so it is compatible with React Native v0.64.x.
It also updates the React Native version of example to v0.64.0
---
Two main changes are introduced in this delivery:
* Update the version of React Native to 0.64.0
This is done to ensure a compatibility with *exclusionList*.
Please note that once React Native Windows is supported it will most likely require the 0.64.x version of both RN and RNW.
* Change all occurrences of `blacklist` to `exclusionList` in *templates/common/example/metro.config.js*

`blacklist` -> `exclusionList` migration for examples metro.config.js

---

packages/create-react-native-library/package.json

When you run  _yarn install_, it's showing warning about @babel/core dependency, and this change removes warnings.

chore: add @babel/core as dev dependency

---

packages/create-react-native-library/templates/cpp-library/android/cpp-adapter.cpp

The `cpp` template has the wrong include header.
```
npx create-react-native-library react-native-simple-turbo
cd react-native-simple-turbo
yarn example android
```

fix: include header with project identifier for cpp

---

packages/create-react-native-library/templates/common/scripts/bootstrap.js

Fixed es lint throwing error without semicolon
I have tested with my repo. You can check here [https://github.com/kyawthura-gg/react-native-skeletons/commit/d30c7b0cb010138086a2da093db03c644c7ab946](https://github.com/kyawthura-gg/react-native-skeletons/commit/d30c7b0cb010138086a2da093db03c644c7ab946)

fix: fixed lint throw error without semicolon

---

packages/create-react-native-library/templates/objc-library/ios/{%- project.name %}.h
packages/create-react-native-library/templates/objc-library/ios/{%- project.name %}.mm

When I use Turbo module, today If I define a new method (on JS side) in my turbo module interface Native{%- project.name %}.ts, codegen generates new files. But I do not have in Xcode any warning or error that tells me to implement this new method.
Find more details in this discussion: #261 
1. Generate a new library with Turbo module <img width="421" alt="image" src="https://user-images.githubusercontent.com/9041221/186720784-280933a9-42be-424d-b182-b5edb7d95d32.png">
2. Add a new function in in the turbo module spec interface : `subtract(a: number, b: number): number;`
3.  In example project run : `pod install`
4. In Xcode open your module file. You should see a warning message. The message is telling that your module does not respect the interface generated by codegen
5. Click on …

feat(ios): enable function generation by Xcode with CodeGen interface

---

README.md
packages/react-native-builder-bob/src/targets/commonjs.ts
packages/react-native-builder-bob/src/targets/module.ts
packages/react-native-builder-bob/src/targets/typescript.ts
packages/react-native-builder-bob/src/utils/compile.ts

- Generate sourcemap for TS declaration files
- Include `sourceRoot` to resolve the source file against
- Don't inline the source code to the sourcemap to reduce size of the map
- Add an option to disable source maps (e.g. if we're not publishing the source)
Closes #279

feat: improve sourcemaps generation

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/common/LICENSE

We are manually updating year when it can be dynamic.
* The following command should not fail.
```
node packages/create-react-native-library/bin/create-react-native-library sample-module
```
* Year in LICENSE should be the device's year.

feat: make year dynamic

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/cpp-view-mixed/android/Android.mk
packages/create-react-native-library/templates/cpp-view-mixed/android/registration.cpp
packages/create-react-native-library/templates/cpp-view-new/android/Android.mk
packages/create-react-native-library/templates/cpp-view-new/android/registration.cpp
packages/create-react-native-library/templates/java-view-mixed/android/src/newarch/{%- project.name %}ViewManagerSpec.java
packages/create-react-native-library/templates/java-view-new/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}ViewManager.java
packages/create-react-native-library/templates/kotlin-view-mixed/android/src/newarch/{%- project.name %}ViewManagerSpec.kt
packages/create-react-native-library/templates/kotlin-view-new/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}ViewManager.kt
packages/create-react-native-library/templates/native-common/android/build.gradle

Ref: https://github.com/callstack/react-native-builder-bob/discussions/359
[`Fabric` was introduced at react-native@0.68](https://reactnative.dev/blog/2022/03/30/version-068#opting-in-to-the-new-architecture), and [full CMake support was introduced at react-native@0.71](https://reactnative.dev/blog/2022/09/05/version-070#full-cmake-support-for-android-builds)
We are working on fabric packages for 0.69 and need fabric template with `Android.mk`
```sh
$ $PATH_TO_BOB_PROJECT/packages/create-react-native-library/bin/create-react-native-library create fabric-compat
...
✔ What type of library do you want to develop? › Fabric view with backward compat
...
$ pushd fabric-compat && yarn install && yalc publish && popd
$ npx react-native@0.69.4 init MyApp --version 0.69.4
$ cd MyApp && yalc add …
```

Backport androidmk

---

packages/react-native-builder-bob/src/utils/compile.ts

The`@babel/plugin-proposal-class-properties` no longer needs to be explicitly added, as it is now incorporated into `@babel/preset-env`. You can see this in a freshly generated RN library by adding `debug: true` to this default configuration:
```
% yarn bob build
yarn run v1.22.19
$ .../rnlib/node_modules/.bin/bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 1 files in src with babel
@babel/preset-env: `DEBUG` option
Using targets:
{
"chrome": "108",
"edge": "108",
"firefox": "108",
"ios": "15.6",
"node": "16",
"safari": "15.6",
"samsung": "19"
}
Using modules transform: commonjs
Using plugins:
proposal-class-static-block { ios, node < 16.11, safari }
proposal-private-property-in-object { node < 16.9 }
syntax-class-properties …
```

fix: remove extra class-props babel plugin

---

packages/create-react-native-library/templates/native-common/android/build.gradle

Fix https://github.com/callstack/react-native-builder-bob/issues/361 which is introduced by https://github.com/callstack/react-native-builder-bob/commit/4eff3ebfcbbb1bc4961c5567ea4d1e75d3c5a72d
According to [outage postmortem](https://reactnative.dev/blog/2023/01/27/71rc1-android-outage-postmortem), we could revert the noinspection version `+` back for react-native@0.70.*

fix: failure noinspection version for 0.69.4

---

lefthook.yml
package.json
packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/common/$package.json
packages/create-react-native-library/templates/common/tsconfig.json
packages/create-react-native-library/templates/native-view-legacy/src/index.tsx
packages/react-native-builder-bob/src/index.ts
tsconfig.json
yarn.lock

fix: typescript 5 compatibility

---

packages/create-react-native-library/templates/native-common/{%- project.identifier %}.podspec

This PR adds support for linking **C files** on iOS.
When creating module with C++ template, files with `.c` extension were not linked correctly.

feat: add C files linking to .podspec file template

---

packages/create-react-native-library/templates/native-common/android/build.gradle

fix: android build.gradle typo

---

packages/react-native-builder-bob/src/targets/commonjs.ts
packages/react-native-builder-bob/src/targets/module.ts
packages/react-native-builder-bob/src/targets/typescript.ts
packages/react-native-builder-bob/src/utils/compile.ts
packages/react-native-builder-bob/src/utils/logger.ts

After initial project setup, it's possible that the location of built files may diverge from value of package.json fields due to configuration changes. Previously it'd go unnoticed.
This adds additional checks after the files are built to ensure that such mismatches cause a build failure.
https://github.com/callstack/react-native-builder-bob/assets/1174278/25d1c427-da3e-4204-b49e-6754c1a316de
- Tested it in React Navigation & React Native Paper repos

feat: verify that the package.json fields point to correct path

---

packages/create-react-native-library/templates/native-common/android/build.gradle

Resolves #394 
> The ideal way this should be tested is with the Android Gradle Plugin 8.0 but it's planned to be introduced with React Native 0.73.
1. Create a new library that includes native Android code (Native Module > Java & Obj-c for instance).
2. Make sure you are able to build the example app on Android.
3. Also make sure you are able to create a release variant of the example app.

feat(android): gradle namespace support for AGP versions >7.3

---

packages/create-react-native-library/templates/objc-library/ios/{%- project.name %}.mm

Closes #414 
We were using `RCT_REMAP_METHOD` to register methods in the current architecture. This macro generates a new method from the given method and changes its signature.
I've changed it to `RCT_EXPORT_METHOD` and with this change, we are able to remove the duplicate implementation for mixed libraries.
These changes can potentially change these libraries: `current arch objc`, `new arch objc`, `new arch cpp`, `mixed arch objc`, `mixed arch cpp`. We need to make sure all of those libraries are generated properly and work well.

refactor: use RCT_EXPORT_METHOD instead of RCT_REMAP_METHOD

---

packages/create-react-native-library/templates/native-common/android/build.gradle
packages/create-react-native-library/templates/native-common/android/src/main/AndroidManifest.xml
packages/create-react-native-library/templates/native-common/android/src/main/AndroidManifestDeprecated.xml
packages/create-react-native-library/templates/native-common/android/src/main/AndroidManifestNew.xml

The React Native CLI relies on the filename `AndroidManifest.xml` to be able parse the package name. But we were using `AndroidManifestLegacy.xml` instead which broke the lib for older RN versions (AGP 7). This change makes it so that we use `AndroidManifest.xml` for older RN versions and `AndroidManifestNew.xml` for newer RN versions.
Fixes #429
- Create an app with RN 0.68 and install the library without these changes - see that `yarn android` fails
- Create an app with RN 0.68 and install the library with these changes - see that `yarn android` succeeds
- Create an app with latest RN and install the library with these changes - see that `yarn android` succeeds

fix: use `AndroidManifest.xml` for older RN versions

---

packages/react-native-builder-bob/package.json
packages/react-native-builder-bob/src/targets/typescript.ts

Closes #434
The builder bob typescript build phase uses `yarn bin` and `npm bin` commands to locate the `tsc`. However, the `npm bin` command is removed with npm 9.0. Please see: https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/
> Both of the test cases start with the following steps:
1. Clone the repo and cd into `packages/react-native-builder-bob`
2. Run `yarn prepack` to build the builder bob.
3. Run `npm link`
4. Create a new project with `npx create-react-native-library@latest my-awesome-project`. You can select `javascript` as the type.
5. Run `npm link react-native-builder-bob` to link the project.
1. Run `npm run prepack` to verify the typescript compilation step works properly.
2. Run `yarn prepack` to verify the typescript compilation step works properly.
3. Run …

feat(builder-bob): dont use npm bin to get tsc path

---

packages/create-react-native-library/templates/native-common/android/build.gradle

`develop mode` condition is inspired by [`react-native-reanimated` build.gradle](https://github.com/software-mansion/react-native-reanimated/blob/main/android/build.gradle)
It uses the lock version of `react-native` dependency of library when compiling `example`
The lock version fails the build when there are different versions of `react-native` in each variant of examples
For example, https://github.com/Sunbreak/lottie-react-native/tree/compat-example
- [apps/fabric](https://github.com/Sunbreak/lottie-react-native/tree/compat-example/apps/fabric) use `react-native@0.71.11`
- [apps/fabric-compat](https://github.com/Sunbreak/lottie-react-native/tree/compat-example/apps/fabric) use `react-native@0.69.4`
https://github.com/lottie-react-native/lottie-react-native/pull/1057 is PR of …

fix: rm mode check in registrationCompat

---

packages/create-react-native-library/src/utils/generateExampleApp.ts
packages/create-react-native-library/templates/common/$package.json

Fixes #443 
Replaced `@react-native-community/eslint-config` with `@react-native/eslint-config`. Please see the PR that changes the name on the React Native repository [here](https://github.com/facebook/react-native/pull/34581)
1. Create a new React Native library
2. cd into the library you have created.
3. run `yarn lint`
4. Make sure linting works properly.

feat(crnl): rn-community/eslint-config -> rn/eslint-config

---

packages/react-native-builder-bob/src/index.ts

I have a library configured with `"type": "module"`. This means that I need to provide `bob.config.cjs`, as `.js` extensions won't do. That config file needs to be explicitly added to the cosmicConfig

Feature: Allow bob.config.cjs

---

package.json
packages/create-react-native-library/babel.config.js
packages/create-react-native-library/package.json
packages/create-react-native-library/templates/common/$package.json
packages/react-native-builder-bob/babel.config.js
packages/react-native-builder-bob/package.json
packages/react-native-builder-bob/src/utils/compile.ts

Node 16 LTS has [reached EOL](https://nodejs.org/en/blog/announcements/nodejs16-eol). And some libraries are dropping the support for it already. In order to support the transition to Node 18 and make sure everything works properly, we can change all the minimum engine versions to 18.
> This needs to be tested with a pure Javascript library which uses Expo, and a library with native code which uses the CLI.
1. Create a new library using `npx create-react-native-library some-cool-name`.
2. Complete creating the library and install the dependencies
3. Build the example app and make sure your library works properly.
4. Run `yarn prepack` to make sure your library is building properly.

chore: bump the engine node version to 18

---

README.md
packages/react-native-builder-bob/src/index.ts
packages/react-native-builder-bob/src/targets/typescript.ts
packages/react-native-builder-bob/src/utils/compile.ts

This adds detection of correct entry points based on the `source` field in `package.json`. Currently it's shown in the error message when the entries are incorrectly configured.
In future, we may automatically update the `package.json` fields to point to the correct paths.
Tested in React Navigation monorepo.

fix: detect entry path and show in error messages

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/src/utils/generateExampleApp.ts
packages/create-react-native-library/src/utils/spawn.ts
packages/react-native-builder-bob/src/targets/typescript.ts

With Yarn 3, the aliases for binaries only seem to exist at the monorepo root `node_modules`, so the current logic fails to find `tsc`. This change uses `yarn bin tsc` to get the correct location for the `tsc` binary.
Tested in the React Navigation monorepo

fix: fix locating `tsc` in yarn 3 workspaces

---

packages/create-react-native-library/templates/native-common/android/build.gradle

> `cmake.abiFilters` specifies the Application Binary Interfaces (ABI) that Gradle should build outputs for. The ABIs that Gradle packages into your APK are determined by `android.defaultConfig.ndk.abiFilter` [link](https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/ExternalNativeCmakeOptions)
- Support for C++ module was introduced at https://github.com/callstack/react-native-builder-bob/commit/6588c5c1caf7e2f17d54f3abd0b5c812f92a9ee2 three years ago
- React Native application template instroduced `reactNativeArchitectures` since https://github.com/facebook/react-native/commit/0f39a1076dc154995a2db79352adc36452f46210 two years ago
None

fix: remove unused cmake abiFilters

---

packages/create-react-native-library/templates/cpp-library/android/CMakeLists.txt
packages/create-react-native-library/templates/java-library-legacy/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}Module.java
packages/create-react-native-library/templates/java-library-mixed/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}Module.java
packages/create-react-native-library/templates/java-library-new/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}Module.java

Doesn't really fix/improve anything, just a nitpick. `cpp` seems too generic. Just close if it's not a welcome change. Thanks!
```
yarn example android
```

chore: use project identifier instead of generic

---

packages/create-react-native-library/templates/cpp-library/android/CMakeLists.txt

Removes CMake warning.
Before:
```
MacBook-Pro:react-native-sample davidangulo$ yarn example android
info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
> Task :react-native-sample:configureCMakeDebug[arm64-v8a]
C/C++: CMake Warning (dev) in CMakeLists.txt:
C/C++:   No project() command is present.  The top-level CMakeLists.txt file must
C/C++:   contain a literal, direct call to the project() command.  Add a line of
C/C++:   code such as
C/C++:     project(ProjectName)
C/C++:   near the top of the file, but after cmake_minimum_required().
C/C++:   CMake is pretending there is a "project(Project)" command on the first
C/C++:   line.
C/C++: This warning is for project developers.  Use -Wno-dev to suppress it.
> Task …
```

chore: remove CMake warning

---

.github/workflows/build-templates.yml
packages/create-react-native-library/templates/common/$.github/workflows/ci.yml

Newer versions of Android Gradle Plugin requires Java 17 to work. We were using Java 11 on workflows. Upgraded them to use Java 17.
I've also noticed sometimes runners fails due to 2G max heap. I've set max heap to 6G.
Android related CI needs to pass.

chore: use java 17 and 6G max heap on workflows 

---

packages/create-react-native-library/templates/cpp-library/android/CMakeLists.txt

```
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Execution failed for task ':react-native-pkce-challenge:buildCMakeDebug[arm64-v8a]'.
mobile/android/../node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:1107:23 error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'? typename = std::enable_if_t< ~~~~~^~~~~~~~~~~ enable_if
```
`enable_if_t` is used by JSI: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/jsi/jsi/jsi.h#L1122
According to https://stackoverflow.com/questions/64281680/error-no-template-named-enable-if-t-in-namespace-std-did-you-mean-enable, the fix is to use C++14 or newer.
React Native JSI itself uses C++14: …

fix: jsi no template error

---

.github/workflows/build-templates.yml
packages/create-react-native-library/templates/common/$.github/workflows/ci.yml

We were using an older version of macOS (macOS 12). As of January 30th, 2024, GitHub announced the new M1 macOS runner. [Here's the link for the blog post](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)
We need to make sure CI passes with the changes

chore: use the macOS 14 with M1 processor runner on workflows

---

.github/actions/setup/action.yml
.github/workflows/build-templates.yml
.github/workflows/check-project.yml
.github/workflows/deploy-docs.yml
.github/workflows/rebase.yml

Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/cache@v3.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
just run workflows...

Node.js 16 actions are deprecated.

---

packages/create-react-native-library/templates/native-common/{%- project.identifier %}.podspec

After https://github.com/callstack/react-native-builder-bob/pull/358 identation become shifted which makes code hard to read and could lead to bugs. For example I was placing package dependencies inside `if/else` block, right after `s.dependency "React-Core"`
see 
| before | after |
|--------|--------|
| <img width="1624" alt="image" src="https://github.com/callstack/react-native-builder-bob/assets/1577804/65a6b479-3e76-4170-b874-b5635b6a5401"> | <img width="1624" alt="image" src="https://github.com/callstack/react-native-builder-bob/assets/1577804/5e3862e7-e6d9-48da-9efd-5c3e5f611749"> |
Purely aesthetic changes, so nothing to break

fix: podspec file indentation

---

packages/create-react-native-library/templates/native-common/android/build.gradle

In the native template `abiFilters` is missing from `externalNativeBuild` block. This means that the library would be built for every available ABI when building the application, even if the application itself is being built for a specific one. This is not that problematic (besides taking more time) when using React Native aar, but when building RN from source the core `.so` files will be built for that specific ABI. In case the library depends on a `.so` file, it would fail at the linking stage due to missing `.so` for the remaining ABIs.
See
- https://github.com/Expensify/App/pull/40102
- https://github.com/Expensify/react-native-live-markdown/pull/284
- https://github.com/margelo/react-native-quick-sqlite/pull/41

Add abiFilters to the native template

---

packages/create-react-native-library/src/utils/generateExampleApp.ts

This disables [Jetifier](https://developer.android.com/tools/jetifier) for the example apps that are generated for native libraries.
This should also fix the CI issues with Java Heap Space errors. [example](https://github.com/callstack/react-native-builder-bob/actions/runs/9463570447/job/26069066456).
1. `cd packages/create-react-native-library`
2. `yarn prepare`
3. `bin/create-react-native-library`
4. Provide email, repo URL etc.
5. Pick any native module type for your lib
6. Pick any language
7. Once the lib is generated go to `example/android/gradle.properties` and make sure `android.enableJetifier` is `false`.

fix: disable jetifier for generated native examples

---

packages/create-react-native-library/src/index.ts

Reverts callstack/react-native-builder-bob#564

Revert "feat: ask to use recommended template"

---

packages/create-react-native-library/src/utils/generateExampleApp.ts

closes #580
Uses the corresponding version of react-native init as specified by the "--version" flag. This allows the module to be used on RNW versions other than "latest" since latest isn't always compatible with every version and a new version may introduce breaking changes.  
Actually wasn't able to test this module locally, the instructions failed for me :( but tested `npx --yes react-native@0.75.0-rc.2 init testcli --directory examples --version 0.75.0-rc.2 --skip-install --npm` to make sure it works as intended.

Uses the corresponding react-native init version

---

packages/create-react-native-library/src/utils/generateExampleApp.ts

With fairly new commands `build-android/ios` added inside React Native Community CLI we can replace manually calling `./gradlew` and `xcodebuild` inside `build:android` and `build:ios` scripts. 
1. Generate new project with `create-react-native-library`
2. `build:android` and `build:ios` scripts should have the same result as before ✅

chore: use `build-android/ios` commands in added scripts inside `example` app

---

packages/create-react-native-library/src/index.ts

i faced the following issue:
Cannot set properties of undefined (setting 'react') /Users/imokhles/.nvm/versions/node/v20.13.1/lib/node_modules/create-react-native-library/lib/index.js:558
rootPackageJson.devDependencies.react = examplePackageJson.dependencies.react;
^
TypeError: Cannot set properties of undefined (setting 'react')
at Object.create [as handler] (/Users/imokhles/.nvm/versions/node/v20.13.1/lib/node_modules/create-react-native-library/lib/index.js:558:43)

fix: devDependencies doesn't exist in rootPackageJson

---

packages/create-react-native-library/src/utils/generateExampleApp.ts

In https://github.com/callstack/react-native-builder-bob/pull/572 we've introduced `test-app` as an option for `example` project, and CRNL contains two scripts `build:ios` and `build:android` that are injected when creating project, RNTA also contains two scripts named in the same way, which are then replaced - in this Pull Request in relevant scenario I added logic which joins two scripts.
1. Create a new project with `create-react-native-library`
2. Choose `test-app` for `example/`
3. `build:ios` and `build:android` should contain logic of creating and bundling app as well as building app with relevant options.

fix: fix `build:ios/android` commands in test-app example

---

packages/create-react-native-library/src/index.ts

A regression introduced in https://github.com/callstack/react-native-builder-bob/pull/572. 
CRNL shouldn't ask for example type in local library scenario.
1. Run `create-react-native-library` under a React Native project.
2. Example project shouldn't be included in the local library.

fix: hide select example question when creating local library

---

packages/create-react-native-library/src/utils/generateExampleApp.ts

Fixes a regression where `build-android` contained a script for building iOS app. 
`build:android` should contain script for building Android app.

fix: add correct script on Android

---

packages/react-native-builder-bob/src/utils/compile.ts

currently these files get treated as assets and are copied over as is. however this is not the correct behavior. this changes them to be trated as source code.
in addition, the module syntax in .mts or .mjs files is preserved as is.
tested in a generated project by creating `.mts` and `.cts` files.

feat: support mts, cts, mjs and cts files in source code

---

docs/pages/esm.md
packages/react-native-builder-bob/src/utils/compile.ts

This will provide more flexibilty to library authors such as specifying `type: module` in their project's `package.json` without breaking the commonjs output for the published code.

fix: always create package.json with type regardless of esm option

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/src/utils/generateExampleApp.ts
packages/create-react-native-library/templates/common/babel.config.js
packages/create-react-native-library/templates/expo-library/example/babel.config.js
packages/create-react-native-library/templates/native-common-example/example/babel.config.js
packages/react-native-builder-bob/babel-preset.js
packages/react-native-builder-bob/package.json
yarn.lock

Previously the React Native Babel preset was being used t compile the library code as well. However, this preset differs from the preset used to publish the library which can introduce inconsistencies.
For example, Metro compiles modules in loose mode which can hide strict mode errors during dev, but they'll surface when consumer uses the library. With this change, we make sure that the same preset is used for dev to avoid the inconsistency.
It also adds a babel plugin to explicitly add `use strict` - as Metro doesn't use strict mode for ESM code which is not spec-compliant, and the behavior differs from the CommonJS build where we add `use strict` during publish.

feat: use the bob preset for the library during dev

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/src/utils/generateExampleApp.ts
packages/create-react-native-library/templates/common-example/example/metro.config.js
packages/create-react-native-library/templates/expo-library/example/babel.config.js
packages/create-react-native-library/templates/expo-library/example/metro.config.js
packages/create-react-native-library/templates/native-common-example/example/babel.config.js
packages/create-react-native-library/templates/native-common-example/example/react-native.config.js
packages/react-native-builder-bob/babel-config.js
packages/react-native-builder-bob/metro-config.js
packages/react-native-builder-bob/package.json
yarn.lock

Currently the example app has metro and babel configs setup to work correctly in the library setup. However, the files are long and verbose - increasing the maintenance cost as the consumer needs to manually update them when we make any changes.
So this moves the configs to `react-native-builder-bob` package, so users can import and use them. They still have the full flexibility to customize anything they need.
Tested by creating an Expo app and app with native modules.

feat: export babel and metro configs to reduce boilerplate

---

packages/create-react-native-library/src/utils/generateExampleApp.ts

When trying to build a vanilla library with a version of React Native 0.76 (e.g 0.76.0-nightly-20240701-9f6cb21ed), the script fails with the following error: 
```
ℹ Using react-native@0.76.0-nightly-20240701-9f6cb21ed for the example
⠹ Generating example app
⚠️ The `init` command is deprecated.
- Switch to npx @react-native-community/cli init for the identical behavior.
- Refer to the documentation for information about alternative tools: https://reactnative.dev/docs/getting-started
C:\new-account-repos\react-native-builder-bob\packages\create-react-native-library\lib\utils\spawn.js:27
reject(new Error(stderr.trim()));
```
Allows creating a vanilla library with CRNL on 0.76 versions of react-native. This issue was hit in the RNW repo where we are trying to …

Update CLI to use `@react-native-community/cli init` instead of `react-native init`

---

packages/react-native-builder-bob/metro-config.js

react-native uses a asset registry package to register assets. seems the library and the example app are using different copies of this package, presumably because Expo CLI embeds `@react-native/assets-registry` verbatim in the code during transform. this causes the library not to use the same copy of the package as `react-native`. this results in broken assets in the app.
with this change we're ensuring that we always load a single version of the package to ensure assets work.
closes #607

fix: ensure assets are registered correctly

---

docs/pages/build.md
docs/pages/esm.md
packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/common/$package.json
packages/react-native-builder-bob/src/index.ts
packages/react-native-builder-bob/src/targets/typescript.ts
packages/react-native-builder-bob/src/utils/compile.ts

This wraps up the ESM support to add support for TypeScript as well. For TypeScript to work correctly, it's necessary to have 2 builds (for ESM and CommonJS). With this, we generate one build and then copy the folder, then add a `package.json` with `type` property for the module system.

feat: add esm build option for typescript

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/common/$package.json

Conditionally add codegen-releated stuff added recently to unblocks the command. 
1. `create-react-native-library`
2. Choose test app as an example
3. `example/` apps should build.

fix: creating library with react-native-test-app example

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/native-library-mixed/react-native.config.js
packages/create-react-native-library/templates/native-library-new/react-native.config.js
packages/create-react-native-library/templates/native-view-mixed/react-native.config.js
packages/create-react-native-library/templates/native-view-new/react-native.config.js

It fixes #627, as we were having the same issue in our react native project.
When opting in Turbo Native Modules or Fabric Views, `cmakeListPath` in generated `react-native.config.js` was not consistent with the hierarchy generated by CodeGen.
This fix corrects the path as stated by document.
If my fix isn't correct, feel free to correct me.
Thank you.
- Select 'Turbo module - requires new arch (experimental)' to create Turbo native module and include it into the project
- Build for android with `npx react-native run-android` to validate the fix was correct.

fix: typo in cmakeListsPath for turbo native modules

---

packages/create-react-native-library/templates/common/$package.json

With the new introduction of https://github.com/callstack/react-native-builder-bob/commit/a90142f471d3c39bd5f9a98c17a64ff23be9b8af#diff-4282562f42ade49c2eb46dee36bcbb7987322efec211330f48387a10e5514678R206 that adds `includeGeneratedCode`, `react-native.config.js` needs to be shipped with the NPM module to signal what directory to use.
Tested `react-native-vector-icons` where I discovered this issue against my project.

fix: make sure react-native.config.json is shipped with each library Fixes #647

---

packages/create-react-native-library/src/utils/generateExampleApp.ts

Fixes #663 
1. Generate a new library with the vanilla example app
2. Make sure you don't get an exception

fix: unknown option npm when generating a vanilla example app

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/common/$package.json
packages/react-native-builder-bob/src/targets/codegen.ts

Fixes #662
1. Create a vanilla example library
2. Make sure `@react-native-community/cli` is added as a dependency
3. make sure `yarn prepare` doesn't throw

fix: vanilla example codegen fails

---

packages/create-react-native-library/templates/common/$package.json

Hey folks, Dependabot is flagging a vulnerability in the vm2 package from this exploit: https://gist.github.com/leesh3288/f693061e6523c97274ad5298eb2c74e9
I think React Native Builder Bob carries that forward through packages: `release-it` -> `proxy-agent` -> `pac-proxy-agent` -> `pac-resolver` -> `degenerator` -> `vm2`
From what I can tell, the vulnerability is basically unused code for any consumer of Builder Bob, but the included versions of `release-it` and `@release-it/conventional-changelog` are also pretty old. Bumping those versions should clean up some Dependabot noise for people who use this tool, and keep everyone up to date.
Hard to actually test since it's a dev dependency that different users will configure differently, but I did some investigation in all the breaking …

chore: bump release-it and release-it conventional changelog versions

---

docs/pages/build.md
packages/create-react-native-library/src/index.ts
packages/react-native-builder-bob/src/index.ts

1. Disables the RNTA temporarily
2. Mentions you need to add `package.json` to your exports in the docs
3. Automatically adds `package.json` with bob if you don't have `includesGeneratedCode: true`.
4. Closes #637 
Currently, there are two approaches with React Native Codegen.
If you have `includesGeneratedCode: true` in your `codegenConfig`, you can generate the Codegen specs in the build time and ship them with your library. This is the recommended way.
If you don't have `includesGeneratedCode: true`, when the application builds, the React Native Codegen is invoked and goes through all the dependencies of the app and generates the codegen specs. However, if you have ESModule exports and if you haven't added your `package.json` to the exports property, then the Codegen __silently__ skips …

feat: disable RNTA temporarily

---

packages/create-react-native-library/src/index.ts

We had a type issue in the `create-react-native-library` index due to using `as const` with a conditional array. I merged this code without checking the CI since it was already failing.
1. Make sure `yarn typecheck` passes.

fix: type issue in crnl index

---

packages/create-react-native-library/src/index.ts

We aren't properly injecting the single-choice questions into our answers yet, and as a result the default example app was testing app. Addressed that problem
1. Create a new library
2. Make sure the example app is a vanilla testing app

fix: every created example app is testing app

---

packages/react-native-builder-bob/src/targets/codegen.ts
packages/react-native-builder-bob/src/utils/runRNCCli.ts

We were using `npx` to call the React Native Community CLI
for codegen. However, not every environment has `npx` available. This
adds custom logic to invoke the RNCCLI only using the node binary.
This also emits a better error message when the user doesn't have `@react-native-community/cli` installed on their library project.
1. Create a new architecture supported library
3. Call `yarn bob build --target codegen`
3. Make sure the command passes without any problems

feat: use node to call codegen

---

packages/create-react-native-library/templates/expo-library/example/App.js
packages/create-react-native-library/templates/expo-library/example/index.js

Generated expo example apps were missing the `index.js` file.
Fixes #682 
1. Create a JS library
2. Run the example app and make sure it displays correctly

fix: expo app doesn't have index.js

---

packages/react-native-builder-bob/src/utils/runRNCCli.ts

The default is set to `yarn`, but an error occurs when using `pnpm` to run `bob build`.
The error arises because the CLI is spawned via Node. Since the CLI in `.bin` is designed to run with Node by default, it should spawn correctly even without explicitly prepending node.
> The changes work correctly even when tested with Yarn.
1. Create a repository using the command:
```sh
> npx create-react-native-library@latest rn-lib
```
3. Remove the `packageManager` field from the `package.json`.
4. Run `pnpm install`
* as-is
5. An error occurs.
* to-be
5. Success.

fix: spawn CLI directly without using Node

---

docs/pages/build.md
packages/react-native-builder-bob/babel-preset.js
packages/react-native-builder-bob/src/utils/compile.ts

In https://github.com/callstack/react-native-builder-bob/commit/0595213e4814c9bc34c270ef89bf31f8e0bd9bed the JSX runtime was changed to `automatic` without the option for the user to opt back in for `classic`.
The `classic` runtime is needed for NativeWind library, which is dependent on Reanimated.
Fixes
- https://github.com/software-mansion/react-native-reanimated/issues/6665
- #678 
🚀

feat: allow to specify JSX Runtime for @babel/preset-react`

---

packages/react-native-builder-bob/src/utils/runRNCCli.ts

Fixes #691
We created a custom way of calling the React Native Community CLI with #685. But it broke the easy workflow with monorepos. We made the original change to be able to call codegen build from XCode actions but since we dropped the support for that, we can revert the change back. This keeps the new file but uses the old method of calling the cil (npx).
1. Create a new project that supports the new architecture
2. Call `yarn prepare` and make sure everything passes.

fix: use npx to call rnccli

---

packages/create-react-native-library/templates/common/$package.json
packages/react-native-builder-bob/src/__tests__/patchCodegenAndroidPackage.test.ts
packages/react-native-builder-bob/src/targets/codegen.ts
packages/react-native-builder-bob/src/utils/patchCodegenAndroidPackage.ts

We were using `type: "all"` in codegenConfig for all types of libraries. @cipolleschi recommended us to use proper types instead [in this thread](https://github.com/facebook/react-native/issues/46208#issuecomment-2491424662). This updates the templates to use the proper types
1. Create a new arch supported module library
2. Go to the `package.json` and make sure `codegenConfig.type` is `"modules"`
3. Make sure the library builds and runs fine with the new architecture
1. Create a new arch supported view/component
2. Go to the `package.json` and make sure `codegenConfig.type` is `"components"`
3. 3. Make sure the library builds and runs fine with the new architecture

fix: use proper codegen types

---

docs/pages/esm.md
packages/create-react-native-library/templates/common/tsconfig.json

This updates the `tsconfig.json` to match metro's behaviour: https://reactnative.dev/blog/2023/06/21/package-exports-support#enabling-package-exports-beta

fix: update tsconfig to align how metro resolves package exports

---

packages/create-react-native-library/templates/common/babel.config.js
packages/react-native-builder-bob/babel-preset.js
packages/react-native-builder-bob/src/types.ts
packages/react-native-builder-bob/src/utils/compile.ts

This removes options parameter from the babel preset and passed them using callers. With this change, Bob can automatically pass relevant parameters to the preset when building without the user to do anything additional if the chose to override the config.
**BREAKING CHANGE**
After this change, consumers can't provide options to the preset directly.

feat: pass options to babel-preset using callers

---

packages/create-react-native-library/src/index.ts

Currently when generating a project, it prints `Using react-native@undefined for the example` due to incorrect check for `undefined` and `null`.

fix: fix incorrect check for --react-native-version

---

packages/create-react-native-library/src/exampleApp/addCodegenBuildScript.ts

@IMPORTANT
feel free to close it if it only fails because a local configuration is incorrect.
Fixed the error "Execution failed for task ':app:invokeLibraryCodegen'" when running yarn android in the Fabric View Library. The invokeLibraryCodegen task now correctly executes npx on all platforms by checking the OS and using cmd or sh accordingly.
Before the fix: Run `yarn android` on example forlder and observe the build failing with the mentioned error.
Apply the fix: Update the build script with the provided solution.
After the fix: Run yarn android again and confirm that the build succeeds without errors.

Fix: Ensure 'invokeLibraryCodegen' task executes 'npx' correctly on all OS

---

packages/create-react-native-library/templates/common-local/$package.json
packages/create-react-native-library/templates/common/$package.json

currently codegen doesn't generate all required files such as `Android.mk`, `CMakeLists.txt` etc. for fabric when type is set to `components`. so we use `all` for now until this bug is fixed.
closes #661

fix: use 'all' for fabric components codegen config

---

.github/workflows/build-templates.yml
packages/create-react-native-library/src/index.ts
packages/create-react-native-library/src/input.ts
packages/create-react-native-library/src/template.ts
packages/create-react-native-library/templates/common-local/$package.json
packages/create-react-native-library/templates/common/$package.json
packages/create-react-native-library/templates/common/CONTRIBUTING.md

This makes the `type` option more readable: e.g. `turbo-module` instead of `module-new`.
It also means our CI builds are easier to read without needing to translate module new to turbo module etc.

refactor: make type option readable and refactor workflow

---

packages/react-native-builder-bob/babel-config.js
packages/react-native-builder-bob/babel-preset.js
packages/react-native-builder-bob/package.json
packages/react-native-builder-bob/src/babel.ts
packages/react-native-builder-bob/src/utils/compile.ts
packages/react-native-builder-bob/src/utils/isFabricComponentFile.ts
yarn.lock

fix: skip compiling fabric view as react native freaks out

---

.github/workflows/build-templates.yml
packages/create-react-native-library/templates/common/$.github/workflows/ci.yml

macos-latest now uses M1 macs. so we don't need to specify macos-14 anymore

chore: change macos-14 to macos-latest

---

packages/create-react-native-library/templates/common/$.github/ISSUE_TEMPLATE/bug_report.yml
packages/create-react-native-library/templates/common/$.github/ISSUE_TEMPLATE/config.yml

This PR adds issue templates for the default template! 
https://github.com/user-attachments/assets/bc85d6e4-f8b8-42a4-8c5f-f542ed9cc8e3
Read through the templates

feat: add issue templates

---

packages/react-native-builder-bob/src/targets/codegen/index.ts
packages/react-native-builder-bob/src/targets/codegen/patches/patchCodegenAndroidPackage.test.ts
packages/react-native-builder-bob/src/targets/codegen/patches/patchCodegenAndroidPackage.ts
packages/react-native-builder-bob/src/targets/codegen/patches/removeCodegenAppLevelCode.test.ts
packages/react-native-builder-bob/src/targets/codegen/patches/removeCodegenAppLevelCode.ts

Fixed #755
There is an effort towards shipping React Native in a prebuilt format on iOS. As a result, some of the codegen-related custom code have to be generated at the build time. However, these changes also affected the codegen generated native code for libraries. This PR patches that behavior on bob level.
Related PRs:
- https://github.com/facebook/react-native/pull/47518
- https://github.com/facebook/react-native/pull/47650
- https://github.com/facebook/react-native/pull/47517
This adds 3 unit test cases to make sure we're able to parse the codegen paths and delete the necessary files.
1. Build bob
1. Create a new library using `npx create-react-native-library`, and pick turbo modules
1. Link the local bob by calling `yarn link path/to/bob --all` in the new library
1. Call `yarn bob …

fix: ios example duplicated symbols due to codegen

---

packages/create-react-native-library/src/template.ts
packages/create-react-native-library/templates/example-module-legacy/example/src/App.tsx

Fixes #754
JS-only libraries were setting the new architecture flag on. While this is not a preferable mental modal, we had some code associated with codegen that checked this flag. With this PR, JS-only libraries will set this flag to false. This is not an optimal solution but we will fully drop this flag with the deprecation of the legacy arch in the upcoming months.
1. Generate a JavaScript-only library
1. Make sure the `codegen` target isn't added to bob targets in `package.json`
1. Make sure there is no `codegenConfig` in `package.json`
1. Make sure `yarn prepare` works.

fix: js-only libraries have codegen config

---

packages/react-native-builder-bob/src/targets/codegen/patches/patchCodegenAndroidPackage.test.ts
packages/react-native-builder-bob/src/targets/codegen/patches/patchCodegenAndroidPackage.ts

Fixes #728
The codegen patcher script was deleting the whole `facebook` namespace when the codegen type was all or module. This was not a problem when the type was module but when the type was all, view manager specs were also getting removed.s
1. Create a new turbo module
2. Set codegen type to all
3. Add turbo module specs
4. Run `yarn bob build --target codegen`
5. Make sure `android/generated/java/com/facebook/react` exists and has view manager specs

fix: bob codegen deletes view specs when codegen type is all

---

packages/create-react-native-library/templates/native-common/android/build.gradle

React Native 0.71 is not longer supported, current React Native version is 0.76.
Android project should build without any issues.

chore: remove React Native 0.71 leftover in `build.gradle`

---

packages/create-react-native-library/templates/native-common/android/build.gradle
packages/create-react-native-library/templates/nitro-module/android/src/main/java/com/margelo/nitro/{%- project.package_dir %}/{%- project.name %}.kt

Android doesn't build at the moment when choosing the new nitro modules implementation.
These changes fixed my issues.

fix(crnl): fix nitro modules android template

---

packages/create-react-native-library/templates/native-common/{%- project.name %}.podspec

Since React Native 0.75 is dropping support soon, I decided to remove this check for 0.71 this makes the `podspec` a lot cleaner.
CI Green

chore: drop 0.71 support from podspec

---

packages/create-react-native-library/templates/common/$package.json

This is a simple fix for the issue encountered when trying to release a new package generated by the library. The solution mainly involved upgrading the dependencies and aligning the configuration.
#733
The fix has been added to the library I am working on, and the issue has been resolved.

fix: update release-it deps and config #733

---

packages/create-react-native-library/src/exampleApp/generateExampleApp.ts

👋 Hey! I was creating a new library and noticed that the generated `example/android/gradle.properties` file had the `newArchEnabled=true` setting duplicated. I think it has to do with the vanilla example app now setting the flag to true by default ([@react-native-community/cli](https://github.com/react-native-community/cli)), but I can't point to a specific commit or dependency that causes it 🤷‍♂️.
In any case, the change should be safe even if they revert it so there's that.
- Create a new library with a vanilla example app and make sure the generated `example/android/gradle.properties` file has no duplicated `newArchEnabled=true` lines.

fix: prevent example app from adding newArchEnabled if already present

---

docs/pages/faq.md
packages/create-react-native-library/src/index.ts
packages/create-react-native-library/src/input.ts
packages/create-react-native-library/templates/common/$package.json
packages/react-native-builder-bob/src/__tests__/__snapshots__/init.test.ts.snap
packages/react-native-builder-bob/src/init.ts

fixes #788
**fabric view**
**turbo module**

fix: fix configuration for fabric view templates

---

packages/react-native-builder-bob/src/build.ts
packages/react-native-builder-bob/src/targets/codegen/patches/patchCodegenAndroidPackage.ts
packages/react-native-builder-bob/src/utils/workerize.ts

This makes the targets run in parallel using node workers instead of concurrently.
Test building in a fresh project.

feat: run tasks in parallel with workers

---

packages/react-native-builder-bob/babel-config.js
packages/react-native-builder-bob/package.json
packages/react-native-builder-bob/src/build.ts
packages/react-native-builder-bob/src/init.ts
packages/react-native-builder-bob/src/utils/loadConfig.ts
yarn.lock

[cosmiconfig](https://github.com/cosmiconfig/cosmiconfig) is no longer maintained. Apart from that, we can't support ESM configuration properly because `cosmiconfig` only supports loading it asynchronously - but we need to be able to load it synchronously in babel config.
I also took a look at [lilconfig](https://github.com/antonk52/lilconfig), but it also has the same limitation.
Node 20.19.0 onwards supports synchronous `require` of ESM, so this limitation is not a technical limitation. So I decided to implement config loading myself since we don't need any advanced features of these config loaders such as traversing up until they find the config.
Tested in a sample project with both `bob build` and in the example app with metro.

refactor: drop cosmiconfig

---

packages/create-react-native-library/templates/native-common/{%- project.name %}.podspec
packages/create-react-native-library/templates/objc-library/ios/{%- project.name %}.h
packages/create-react-native-library/templates/objc-view-new/ios/{%- project.name %}View.mm

- Some people are having XCode build issues with new-architecture enabled libraries, fabric and turbo modules.
- The issues are related to XCode not being able to resolve `#import` directives following this pattern `generated/x/y.h`
- This PR changes the template so these headers are imported from the generated LLVM module using the module include paths such as: `<ModuleName/header.h>`
- Also made all the headers private. Otherwise the modules fail when user tries to add a Swift file. This is because cocoapods automatically generates an umbrella header based on all the available headers and the swift compilation step treats all headers in the umbrella header as objective-c headers. This in turn results in an error since some headers need objective-cpp features and cpp stdlib headers.
1. …

fix(crnl): certain versions of XCode can't resolve codegen headers

---

docs/pages/build.md
docs/pages/esm.md
packages/create-react-native-library/templates/common/$package.json
packages/react-native-builder-bob/src/__tests__/__snapshots__/init.test.ts.snap
packages/react-native-builder-bob/src/init.ts
packages/react-native-builder-bob/src/targets/typescript.ts

There's a possibility of [dual package hazard](https://nodejs.org/docs/latest-v19.x/api/packages.html#dual-package-hazard) with the current setup. Metro enables `exports` support from [0.82.0](https://github.com/facebook/metro/releases/tag/v0.82.0), so this can become a problem for some packages.
So this drops the dual package setup in favor of an ESM-only setup. To make a similar change in your package, apply the following change to your entrypoints:
```diff
-  "main": "./lib/commonjs/index.js",
+  "main": "./lib/module/index.js",a
-  "types": "./lib/typescript/commonjs/src/index.d.ts",
"exports": {
".": {
-      "import": {
-        "types": "./lib/typescript/module/src/index.d.ts",
-        "default": "./lib/module/index.js"
-      },
-      "require": {
-        "types": …
```

refactor: drop commonjs build from default setup

---

packages/create-react-native-library/src/index.ts
packages/react-native-builder-bob/src/targets/codegen/index.ts
packages/react-native-builder-bob/src/targets/codegen/patches/removeCodegenAppLevelCode.ts

https://github.com/facebook/react-native/commit/98b8f178110472e5fed97de80766c03b0b5e988c adds support for `--source` flag in `npx @react-native-community/cli codegen`. With this flag, we can opt out of our patch. With this PR, bob checks if this flag is supported and uses it if it is.
1. Generate a library with a React Native version that supports `--source`. (The baseline is `react-native@0.78.0`).
2. Run `yarn prepare`
3. Make sure the command runs with no errors
4. Check the `ios/generated` and make sure there are no `.podspec` files.

fix: pass source flag to codegen cli when possible

---

docs/pages/build.md

Flow links to TypeScript homepage.

docs: correct flow homepage url

---

packages/create-react-native-library/src/exampleApp/dependencies.ts
packages/create-react-native-library/templates/common/$package.json
packages/create-react-native-library/templates/common/babel.config.js

This uses the react native babel preset for compiling `node_modules` - mainly useful for tests, so that syntaxes such as Flow are handled.
Related to ##747

fix: use react native babel config for node_modules

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/src/inform.ts
packages/create-react-native-library/src/template.ts
packages/create-react-native-library/src/utils/local.ts
packages/create-react-native-library/src/utils/packageManager.ts

- `create-react-native-library` will install `react-native-nitro-modules` automatically for local libraries.
1. Create a new RN app
2. Build the bob repo
3. Link `create-react-native-library` to your RN app
4. Run `create-react-native-library` in the app
5. Answer yes when you're asked if you want to create a native module
6. Select `Nitro Modules`
7. Make sure `react-native-nitro-modules` is added to your app's dependencies.

feat(crnl): install nitro modules dependency automatically for local modules

---

docs/pages/create.md

Replaced outdated links with updated working versions to improve navigation and prevent 404s.

docs: fix dead links in documentation

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/src/inform.ts
packages/create-react-native-library/src/input.ts
packages/create-react-native-library/src/template.ts
packages/create-react-native-library/src/utils/assert.ts
packages/create-react-native-library/src/utils/local.ts
packages/create-react-native-library/src/utils/prompt.ts

this adds `--interactive` and `--non-interactive` arguments.
it is automatically disabled on non-interactive terminals and CI

feat: add non-interactive mode

---

docs/pages/esm.md

As people start using package.json exports more, it might be worth highlighting the "usual" exports people might want to have, which includes expo config plugin files (app.plugin.js).
Feel free to close if you see this being out of scope.
Thank you :)

docs: document app.plugin.js in package.json exports

---

packages/create-react-native-library/templates/native-common/android/build.gradle

Enables support for 16 KB page sizes on Android.
Each Native Module library will need to add this for themselves too in their `build.gradle` file if they want to support 16 KB page sizes, but it's good to have it in the template now I think.
See [Support 16 KB page sizes](https://developer.android.com/guide/practices/page-sizes) for more information.

feat: Enable 16 KB page size on Android

---

packages/create-react-native-library/templates/common/$.github/ISSUE_TEMPLATE/bug_report.yml

Fix bug report issue template not displaying properly due to invalid `render: js` property.
- Removed invalid `render: js` property from bug report template
- Issue template now displays correctly in GitHub Issues interface
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#input

fix(template): remove invalid render property from bug report template

---

.github/actions/setup/action.yml
.github/workflows/build-templates.yml
.github/workflows/check-project.yml
.github/workflows/deploy-docs.yml
.github/workflows/rebase.yml
packages/create-react-native-library/templates/common/$.github/actions/setup/action.yml
packages/create-react-native-library/templates/common/$.github/workflows/ci.yml

Pin GitHub Actions to commit SHAs for safety.

chore: pin GH Actions

---

packages/create-react-native-library/templates/native-common/{%- project.name %}.podspec

See https://github.com/facebook/react-native/issues/52366#issuecomment-3077780700

fix: Remove folly flags that make Nitro Views crash with SIGABRT on RN 0.80

---

packages/create-react-native-library/src/input.ts

Currently, the library validation prevents creating projects in directories that contain any files, including `.git` folders. This creates a frustrating user experience when:
1. Users clone an empty GitHub repository
2. The directory contains only a `.git` folder
3. The validation fails with "Directory already exists" error
This is a common workflow where developers create a GitHub repo first, then clone it locally to set up their React Native library.
- Treat directories as "empty" if they contain no files OR only a `.git` folder
- Allow project creation in such directories
This follows the same pattern used by Vite's `create-vite` tool:
- [Vite source code](https://github.com/vitejs/vite/blob/b135918b91e8381c50bd2d076d40e9a65fe68bfe/packages/create-vite/src/index.ts#L589)
1. yarn …

fix: allow project creation in directories with only .git folder

---

packages/create-react-native-library/templates/common/CONTRIBUTING.md

Removing one unnecessary dot in `create-react-native-library` template `CONTRIBUTING.md`.
Biggest open source contribution in history of open source contributions..

docs: remove excessive dot in CONTRIBUTING.md
