callstack/react-native-builder-bob

templates/library/$.gitattributes
templates/library/example/$package.json
templates/library/example/android/app/build.gradle
templates/library/example/android/app/src/debug/java/com/<%= project.name %>Example/ReactNativeFlipper.java
templates/library/example/android/app/src/main/AndroidManifest.xml
templates/library/example/android/app/src/main/java/com/<%= project.name %>Example/MainApplication.java
templates/library/example/android/build.gradle
templates/library/example/android/gradle.properties
templates/library/example/android/gradle/wrapper/gradle-wrapper.properties
templates/library/example/android/gradlew
templates/library/example/ios/<%= project.name %>Example/AppDelegate.m
templates/library/example/ios/Podfile

upgrade RN version from example to 0.62 using https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0
Flipper integration is vital for debug RN applications, and RN 0.62 has full integration with it.
| Android |    ✅     |

feat: upgrade RN version from example to 0.62

---

src/cli.ts

closes #44 
| iOS     |    ✅❌     |
| Android |    ✅❌     |

feat: show help information if no args were passed

---

src/cli.ts

https://yargs.js.org/docs/#api-recommendcommands
| iOS     |    ✅❌     |
| Android |    ✅❌     |

feat: recommend the closest match to an unknown command

---

templates/common/$package.json

Packages are shipping `__tests__` to prod, these don't serve any purpose in production afaict. 
`npm pack` should show files with `__tests__` being bundled without this change, with it they won't be bundled in the tar file.

chore: ignore __tests__

---

src/create.ts
templates/native-library/<%= project.podspec %>.podspec
templates/native-library/ios/<%= project.name %>.xcodeproj/project.pbxproj
templates/swift-library/ios/<%= project.name %> .swift
templates/swift-library/ios/<%= project.name %>-Bridging-Header.h
templates/swift-library/ios/<%= project.name %>.m

This PR adds the option to create a native module with swift for iOS.
Adresses https://github.com/react-native-community/bob/issues/54
| Android |    ❌     |

feat: add native swift option

---

src/utils/compile.ts

Hi there
My goal is ignoring __mocks__ folder  during the build
nothing
nothing

fix: include mocks in ignore config

---

templates/native-library/{%= project.podspec %}.podspec

React Native's iOS target is 10.0

Update iOS platform to iOS 10

---

package.json
types/is-git-dirty.d.ts
yarn.lock

chore: update is-git-dirty

---

templates/common/example/src/App.tsx
templates/native-library/android/src/main/java/com/{%= project.package %}/{%= project.name %}Package.kt
templates/native-library/android/src/main/java/com/{%= project.package %}/{%= project.name %}ViewManager.kt
templates/native-library/src/index.tsx
templates/objc-library/ios/{%= project.name %}ViewManager.m
templates/swift-library/ios/{%= project.name %}-Bridging-Header.h
templates/swift-library/ios/{%= project.name %}ViewManager.m
templates/swift-library/ios/{%= project.name %}ViewManager.swift

Updated templates to include examples for UI Managers in Kotlin, ObjC and Swift. View displays a box, which can change its background color by passing `color` prop (hex color).
1. Build the latest `bob`, generate project with `Kotlin/Obj` or `Kotlin/Swift` modules
2. Run example App, confirm the view is displayed.
```react
<MyViewManager color="#32a852" style={styles.box} />
```
| Android |    ✅    |

feat: native view managers

---

templates/common/$package.json

Fixes #86
1. Build the latest bob, generate project with "JavaScript module with Expo example and Web support"
2. Verify `"root": true,` is present in generated `package.json file

fix: eslint config in package.json

---

README.md

Fixed url of CircleCI badge in README
Badge is showing the correct result
URL working as expected

docs: fix build badge url

---

README.md

docs: add a FAQ on what to do for react-native libraries

---

packages/create-react-native-library/src/index.ts
packages/create-react-native-library/templates/example/example/android/app/build.gradle
packages/create-react-native-library/templates/example/example/android/app/src/main/java/com/example/{%- project.package %}/MainApplication.java
packages/create-react-native-library/templates/example/example/android/settings.gradle
packages/create-react-native-library/templates/example/example/ios/Podfile

https://user-images.githubusercontent.com/1174278/113693700-2babad00-96cf-11eb-8d16-171b3e142d43.mp4
Which languages do you want to use?
- Java & Objective-C
- Java & Swift
- Kotlin & Objective-C
- Kotlin & Swift
- C++ for both iOS & Android
- JavaScript only
For Java, Kotlin, Swift & Objective-C:
What type of library do you want to develop?
- Native module (to expose native APIs)
- Native view (to use as a component)
For JavaScript only:
What type of example app do you want to generate?
- JavaScript only (with Expo and Web support)
- Native (to use other libraries with native code)

refactor: organize prompt to separate sections

---

packages/create-react-native-library/templates/common/LICENSE

Update LICENSE to 2021

---

packages/create-react-native-library/templates/cpp-library/android/CMakeLists.txt
packages/create-react-native-library/templates/cpp-library/cpp/{%- project.identifier %}.cpp
packages/create-react-native-library/templates/cpp-library/ios/{%- project.name %}.h

Fix cpp example

---

packages/create-react-native-library/templates/common/$package.json

Update typescript to latest version.

update typescript dependency version

---

packages/create-react-native-library/templates/common/LICENSE

chore: update LICENSE to 2022

---

packages/create-react-native-library/templates/objc-view-mixed/ios/{%- project.name %}ViewManager.mm

fix: missing colorToConvert to json

---

docs/theme.config.jsx

docs: add favicon👷‍♂️

---

packages/create-react-native-library/templates/common/$package.json
packages/create-react-native-library/templates/native-common/{%- project.identifier %}.podspec

https://github.com/callstack/react-native-builder-bob/issues/432

[#432] Update of dependencies in template

---

packages/create-react-native-library/package.json
packages/react-native-builder-bob/babel-preset.js
packages/react-native-builder-bob/package.json
yarn.lock

fix: update babel preset to include class transforms for hermes

---

packages/create-react-native-library/templates/common/$package.json

I typed .json instead of .js in the last commit

fix: add react-native.config.js to the published file list

---

packages/create-react-native-library/src/input.ts

New Arch is not experimental anymore! 🎉
N/A

fix: remove experimental from new arch

---

packages/react-native-builder-bob/src/utils/runRNCCli.ts

If an error occurs, it is not printed in the CLI.
* as-is:
* to-be:
1. `react-native-config.js` file: 
```js
test // That code will cause an error.
```
2. yarn prepare

fix(cli): update stdio options to capture error output

---

packages/create-react-native-library/templates/kotlin-library-mixed/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}Package.kt
packages/create-react-native-library/templates/kotlin-library-new/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}Package.kt

Reference https://github.com/reactwg/react-native-new-architecture/pull/249

fix: move from TurboReactPackage to BaseReactPackage

---

packages/react-native-builder-bob/babel-preset.js
packages/react-native-builder-bob/package.json
yarn.lock

feat: enable JS codegen transform

---

packages/create-react-native-library/templates/kotlin-library-new/android/src/main/java/com/{%- project.package_dir %}/{%- project.name %}Package.kt

reference: https://github.com/facebook/react-native/blob/5c789c3d3a91f4e4ee06e97cdeec7dcb64a5cf44/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/module/model/ReactModuleInfo.kt#L25

fix: remove deprecated hasConstants parameter

---

packages/create-react-native-library/templates/native-common/{%- project.identifier %}.podspec

fix: codegen generated headers are public on ios

---

packages/create-react-native-library/templates/native-common/android/build.gradle
packages/create-react-native-library/templates/native-common/android/gradle.properties

There are some outdated values, I synced them with what is currently inside template: https://github.com/react-native-community/template/blob/f4aa4a9817b4381a108e19040fe3b3515cc531bc/template/android/build.gradle
CI

feat(android): upgrade SDK versions and build tools

---

packages/create-react-native-library/templates/common/$.gitignore

Adding `.xcode.env.local` to the `.gitignore`

chore: adding .xcode.env.local to $.gitignore

---

packages/create-react-native-library/templates/nitro-module/android/src/main/java/com/margelo/nitro/{%- project.package_dir %}/{%- project.name %}.kt

- Fixes https://github.com/callstack/react-native-builder-bob/issues/768

fix: Import `@DoNotStrip`

---

README.md

- Adds a banner image to README
- Make sure the README is rendered properly.

chore: add banner image to readme

---

packages/create-react-native-library/templates/common/CONTRIBUTING.md

fix(template): replace XCode with Xcode

---

packages/create-react-native-library/templates/objc-library/ios/{%- project.name %}.mm

Updates iOS `.mm` TurboModule template file to match https://reactnative.dev/docs/turbo-native-modules-introduction#4-write-your-native-platform-code
Module generates correctly, app consuming it builds as expected

chore: update iOS TurboModule template
